thread: thread.c
	gcc -lpthread thread.c -o thread

multthread: multthread.c
	gcc -lpthread multthread.c -o multthread

multthreadmutx: multthreadmutex.c 
	gcc -lpthread multthreadmutex.c -o multthreadmutex

varthread: varthread.c
	gcc -lpthread varthread.c -o varthread
